# Docker Compose es una herramienta que facilita la definición
#  y ejecución de aplicaciones multi-contenedor. 

version: '3'  # Especifica la versión del formato de Docker Compose que se está utilizando.

services:  # Define los servicios que se van a ejecutar.
  postgres:  # Nombre del servicio, en este caso, una base de datos PostgreSQL.
    image: postgres  # Imagen de Docker que se utilizará para este servicio.
    restart: always  # Política de reinicio, asegura que el contenedor se reinicie automáticamente si falla.
    environment:  # Variables de entorno para configurar el contenedor.
      - POSTGRES_USER  # Nombre de usuario para la base de datos PostgreSQL.
      - POSTGRES_PASSWORD  # Contraseña para el usuario de la base de datos PostgreSQL.
    volumes:  # Montajes de volúmenes para persistencia de datos. cada que creamos una imagen, usamos un volúmen para no perder lo que tenemos en la base de datos
        - ./database:/var/lib/postgresql/data # Usamos volúmenes para persistir los datos de PostgreSQL en el directorio local ./database.
        - ./ddl:/ddl # Montaje adicional para scripts de definición de datos (DDL).
  app: # Nombre del servicio, en este caso, la aplicación principal.
    build: # Instrucciones para construir la imagen de Docker.
      context: .  # Contexto de construcción, en este caso, el directorio actual.
    volumes:  # Montajes de volúmenes para persistencia de datos y logs.
      - ./app:/app # Montaje del código de la aplicación usamos nodemon para iniciar la aplicación automáticamente.
      - ./devLogs:/logs # Montaje de los logs de desarrollo.
    ports: # Puertos expuestos para acceder a la aplicación.
      - '3000:3000'  # Mapea el puerto 3000 del host al puerto 3000 del contenedor.
    depends_on: # Define dependencias entre servicios.
      - 'postgres' # Este servicio depende del servicio 'postgres'.
    environment:  # Variables de entorno para configurar el contenedor.
      - NODE_ENV  # Entorno de ejecución de Node.js (desarrollo, producción, etc.).
      - POSTGRES_USER  # Nombre de usuario para la base de datos PostgreSQL.
      - POSTGRES_PASSWORD # Contraseña para el usuario de la base de datos PostgreSQL.
      - POSTGRES_PORT # Puerto en el que se ejecuta PostgreSQL.
      - POSTGRES_HOST # Host donde se encuentra PostgreSQL.


